# -*- coding: utf-8 -*-
"""Google Play Store. (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19uZEh_gc1o-KoIPyW54TArozozA5fG9w
"""

#IMPORTING LIBRARIES.

import pandas as pd
import numpy as np
import datetime

#LOADING DATA.
data  = pd.read_csv("/content/googleplaystore(impure).csv")



#CHECKING FOR NULL VALUES.
data.isnull().sum()

#dropping null values
data.dropna(inplace=True)

#Dropping unnecessary columns
data.drop(columns='Unnamed: 0', inplace=True)

data

#CHANGING DATE TIME TO DESIRED FORMAT.
data['Last Updated']=  pd.to_datetime(data['Last Updated'],errors='coerce')

data.info()

data['Last Updated'] =data['Last Updated'].dt.strftime('%Y-%m-%d')

data['Last Updated']=  pd.to_datetime(data['Last Updated'],errors='coerce')

data.info()

#CLEANING INSTALL COLUMNS
data['Installs']= data['Installs'].str.replace('+','')
data['Installs']= data['Installs'].str.replace(',','')

data['Installs']=data['Installs'].astype(int)

#CLEANING REVIEWS COLUMN.
data.drop(data[data['Reviews']=='3.0M'].index,inplace=True)

data['Reviews']= data['Reviews'].astype(int)

data.info()

#CLEANING PRICE COLUMN.
data['Price']=data['Price'].str.replace('$','')
data['Price']= data['Price'].astype(float)

data.info()

data.isnull().sum()

#NOW OUR DATAFRAME IS CLEANED WE WILL DUMP IT.

data.to_csv('playstore.csv', index=False)

